services:
  postgres:
    image: postgres:latest
    container_name: newPostgres2
    environment:
      POSTGRES_USER: shanto
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: shanto323
    volumes:
      - ./auth-service/up.sql:/docker-entrypoint-initdb.d/up.sql
    ports:
      - 5432:5432
    restart: unless-stopped

  auth:
    build:
      context: .
      dockerfile: auth-service/app.dockerfile
    env_file:
      - .env
    depends_on: 
      - postgres
    restart: on-failure

  gateway:
    build:
      context: .
      dockerfile: gateway/app.dockerfile
    env_file:
      - .env
    depends_on: 
      - auth
    ports:
      - 8080:8080
    restart: on-failure

  
