services:
  postgres:
    image: postgres:latest
    container_name: newPostgres2
    environment:
      POSTGRES_USER: shanto
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: shanto323
    volumes:
      - ./wallet-service/up.sql:/docker-entrypoint-initdb.d/up.sql
    ports:
      - 5432:5432
    restart: on-failure
  

  
