services:
  postgres:
    image: postgres:latest
    container_name: newPostgres1
    environment:
      POSTGRES_USER: shanto
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: shanto323
    volumes:
      - ./auth-service/up.sql:/docker-entrypoint-initdb.d/1up.sql
      - ./settlement/up.sql:/docker-entrypoint-initdb.d/2up.sql
    ports:
      - 5432:5432
    restart: unless-stopped

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka1
    env_file:
      - .env
    ports:
      - 9092:9092
      - 9093:9093
    volumes:
      - kraft:/bitnami/kafka
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog:latest
    platform: linux/amd64
    container_name: mailhog-service-1
    ports:
      - 1025:1025
      - 8025:8025
    restart: unless-stopped

  auth:
    build:
      context: .
      dockerfile: auth-service/app.dockerfile
    env_file:
      - .env
    depends_on:
      - postgres
    restart: on-failure

  gateway:
    build:
      context: .
      dockerfile: gateway/app.dockerfile
    env_file:
      - .env
    depends_on:
      - auth
      - kafka
    ports:
      - 8080:8080
    restart: on-failure

  notification:
    build:
      context: .
      dockerfile: notification-service/app.dockerfile
    env_file:
      - .env
    depends_on:
      - kafka
      - mailhog
    restart: on-failure

  settlement:
    build:
      context: .
      dockerfile: settlement/app.dockerfile
    env_file:
      - .env
    depends_on:
      - kafka
    restart: on-failure

volumes:
  kraft:
