// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: card.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Card struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Number        string                 `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	Brand         string                 `protobuf:"bytes,3,opt,name=brand,proto3" json:"brand,omitempty"`
	ExpMonth      int32                  `protobuf:"varint,4,opt,name=exp_month,json=expMonth,proto3" json:"exp_month,omitempty"`
	ExpYear       int32                  `protobuf:"varint,5,opt,name=exp_year,json=expYear,proto3" json:"exp_year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_card_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_card_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_card_proto_rawDescGZIP(), []int{0}
}

func (x *Card) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Card) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *Card) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *Card) GetExpMonth() int32 {
	if x != nil {
		return x.ExpMonth
	}
	return 0
}

func (x *Card) GetExpYear() int32 {
	if x != nil {
		return x.ExpYear
	}
	return 0
}

// CARD SECTION
type AddCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Card          *Card                  `protobuf:"bytes,2,opt,name=card,proto3" json:"card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCardRequest) Reset() {
	*x = AddCardRequest{}
	mi := &file_card_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCardRequest) ProtoMessage() {}

func (x *AddCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_card_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCardRequest.ProtoReflect.Descriptor instead.
func (*AddCardRequest) Descriptor() ([]byte, []int) {
	return file_card_proto_rawDescGZIP(), []int{1}
}

func (x *AddCardRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *AddCardRequest) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

type AddCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Card          []*Card                `protobuf:"bytes,1,rep,name=card,proto3" json:"card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCardResponse) Reset() {
	*x = AddCardResponse{}
	mi := &file_card_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCardResponse) ProtoMessage() {}

func (x *AddCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_card_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCardResponse.ProtoReflect.Descriptor instead.
func (*AddCardResponse) Descriptor() ([]byte, []int) {
	return file_card_proto_rawDescGZIP(), []int{2}
}

func (x *AddCardResponse) GetCard() []*Card {
	if x != nil {
		return x.Card
	}
	return nil
}

type GetCardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardsRequest) Reset() {
	*x = GetCardsRequest{}
	mi := &file_card_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardsRequest) ProtoMessage() {}

func (x *GetCardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_card_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardsRequest.ProtoReflect.Descriptor instead.
func (*GetCardsRequest) Descriptor() ([]byte, []int) {
	return file_card_proto_rawDescGZIP(), []int{3}
}

func (x *GetCardsRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type GetCardsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Card          []*Card                `protobuf:"bytes,1,rep,name=card,proto3" json:"card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardsResponse) Reset() {
	*x = GetCardsResponse{}
	mi := &file_card_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardsResponse) ProtoMessage() {}

func (x *GetCardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_card_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardsResponse.ProtoReflect.Descriptor instead.
func (*GetCardsResponse) Descriptor() ([]byte, []int) {
	return file_card_proto_rawDescGZIP(), []int{4}
}

func (x *GetCardsResponse) GetCard() []*Card {
	if x != nil {
		return x.Card
	}
	return nil
}

type RemoveCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid           string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveCardRequest) Reset() {
	*x = RemoveCardRequest{}
	mi := &file_card_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCardRequest) ProtoMessage() {}

func (x *RemoveCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_card_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCardRequest.ProtoReflect.Descriptor instead.
func (*RemoveCardRequest) Descriptor() ([]byte, []int) {
	return file_card_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveCardRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RemoveCardRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type RemoveCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveCardResponse) Reset() {
	*x = RemoveCardResponse{}
	mi := &file_card_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCardResponse) ProtoMessage() {}

func (x *RemoveCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_card_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCardResponse.ProtoReflect.Descriptor instead.
func (*RemoveCardResponse) Descriptor() ([]byte, []int) {
	return file_card_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveCardResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type DeleteCardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCardsRequest) Reset() {
	*x = DeleteCardsRequest{}
	mi := &file_card_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCardsRequest) ProtoMessage() {}

func (x *DeleteCardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_card_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCardsRequest.ProtoReflect.Descriptor instead.
func (*DeleteCardsRequest) Descriptor() ([]byte, []int) {
	return file_card_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteCardsRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type DeleteCardsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCardsResponse) Reset() {
	*x = DeleteCardsResponse{}
	mi := &file_card_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCardsResponse) ProtoMessage() {}

func (x *DeleteCardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_card_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCardsResponse.ProtoReflect.Descriptor instead.
func (*DeleteCardsResponse) Descriptor() ([]byte, []int) {
	return file_card_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteCardsResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_card_proto protoreflect.FileDescriptor

const file_card_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"card.proto\x12\x02pb\"|\n" +
	"\x04Card\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06number\x18\x02 \x01(\tR\x06number\x12\x14\n" +
	"\x05brand\x18\x03 \x01(\tR\x05brand\x12\x1b\n" +
	"\texp_month\x18\x04 \x01(\x05R\bexpMonth\x12\x19\n" +
	"\bexp_year\x18\x05 \x01(\x05R\aexpYear\"@\n" +
	"\x0eAddCardRequest\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x1c\n" +
	"\x04card\x18\x02 \x01(\v2\b.pb.CardR\x04card\"/\n" +
	"\x0fAddCardResponse\x12\x1c\n" +
	"\x04card\x18\x01 \x03(\v2\b.pb.CardR\x04card\"#\n" +
	"\x0fGetCardsRequest\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\"0\n" +
	"\x10GetCardsResponse\x12\x1c\n" +
	"\x04card\x18\x01 \x03(\v2\b.pb.CardR\x04card\"5\n" +
	"\x11RemoveCardRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\"&\n" +
	"\x12RemoveCardResponse\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"&\n" +
	"\x12DeleteCardsRequest\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\"'\n" +
	"\x13DeleteCardsResponse\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg2\xf5\x01\n" +
	"\vCardService\x122\n" +
	"\aAddCard\x12\x12.pb.AddCardRequest\x1a\x13.pb.AddCardResponse\x125\n" +
	"\bGetCards\x12\x13.pb.GetCardsRequest\x1a\x14.pb.GetCardsResponse\x12;\n" +
	"\n" +
	"RemoveCard\x12\x15.pb.RemoveCardRequest\x1a\x16.pb.RemoveCardResponse\x12>\n" +
	"\vDeleteCards\x12\x16.pb.DeleteCardsRequest\x1a\x17.pb.DeleteCardsResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_card_proto_rawDescOnce sync.Once
	file_card_proto_rawDescData []byte
)

func file_card_proto_rawDescGZIP() []byte {
	file_card_proto_rawDescOnce.Do(func() {
		file_card_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_card_proto_rawDesc), len(file_card_proto_rawDesc)))
	})
	return file_card_proto_rawDescData
}

var file_card_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_card_proto_goTypes = []any{
	(*Card)(nil),                // 0: pb.Card
	(*AddCardRequest)(nil),      // 1: pb.AddCardRequest
	(*AddCardResponse)(nil),     // 2: pb.AddCardResponse
	(*GetCardsRequest)(nil),     // 3: pb.GetCardsRequest
	(*GetCardsResponse)(nil),    // 4: pb.GetCardsResponse
	(*RemoveCardRequest)(nil),   // 5: pb.RemoveCardRequest
	(*RemoveCardResponse)(nil),  // 6: pb.RemoveCardResponse
	(*DeleteCardsRequest)(nil),  // 7: pb.DeleteCardsRequest
	(*DeleteCardsResponse)(nil), // 8: pb.DeleteCardsResponse
}
var file_card_proto_depIdxs = []int32{
	0, // 0: pb.AddCardRequest.card:type_name -> pb.Card
	0, // 1: pb.AddCardResponse.card:type_name -> pb.Card
	0, // 2: pb.GetCardsResponse.card:type_name -> pb.Card
	1, // 3: pb.CardService.AddCard:input_type -> pb.AddCardRequest
	3, // 4: pb.CardService.GetCards:input_type -> pb.GetCardsRequest
	5, // 5: pb.CardService.RemoveCard:input_type -> pb.RemoveCardRequest
	7, // 6: pb.CardService.DeleteCards:input_type -> pb.DeleteCardsRequest
	2, // 7: pb.CardService.AddCard:output_type -> pb.AddCardResponse
	4, // 8: pb.CardService.GetCards:output_type -> pb.GetCardsResponse
	6, // 9: pb.CardService.RemoveCard:output_type -> pb.RemoveCardResponse
	8, // 10: pb.CardService.DeleteCards:output_type -> pb.DeleteCardsResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_card_proto_init() }
func file_card_proto_init() {
	if File_card_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_card_proto_rawDesc), len(file_card_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_card_proto_goTypes,
		DependencyIndexes: file_card_proto_depIdxs,
		MessageInfos:      file_card_proto_msgTypes,
	}.Build()
	File_card_proto = out.File
	file_card_proto_goTypes = nil
	file_card_proto_depIdxs = nil
}
