// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: transection.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentStatus int32

const (
	PaymentStatus_PAYMENT_STATUS_COMPLETED PaymentStatus = 0
	PaymentStatus_PAYMENT_STATUS_ERROR     PaymentStatus = 1
	PaymentStatus_PAYMENT_STATUS_PENDING   PaymentStatus = 2
	PaymentStatus_PAYMENT_STATUS_REVERSED  PaymentStatus = 3
)

// Enum value maps for PaymentStatus.
var (
	PaymentStatus_name = map[int32]string{
		0: "PAYMENT_STATUS_COMPLETED",
		1: "PAYMENT_STATUS_ERROR",
		2: "PAYMENT_STATUS_PENDING",
		3: "PAYMENT_STATUS_REVERSED",
	}
	PaymentStatus_value = map[string]int32{
		"PAYMENT_STATUS_COMPLETED": 0,
		"PAYMENT_STATUS_ERROR":     1,
		"PAYMENT_STATUS_PENDING":   2,
		"PAYMENT_STATUS_REVERSED":  3,
	}
)

func (x PaymentStatus) Enum() *PaymentStatus {
	p := new(PaymentStatus)
	*p = x
	return p
}

func (x PaymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_transection_proto_enumTypes[0].Descriptor()
}

func (PaymentStatus) Type() protoreflect.EnumType {
	return &file_transection_proto_enumTypes[0]
}

func (x PaymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentStatus.Descriptor instead.
func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_transection_proto_rawDescGZIP(), []int{0}
}

type Transection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Status        PaymentStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=pb.PaymentStatus" json:"status,omitempty"`
	SenderId      string                 `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ReceiverId    string                 `protobuf:"bytes,4,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Note          string                 `protobuf:"bytes,6,opt,name=note,proto3" json:"note,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transection) Reset() {
	*x = Transection{}
	mi := &file_transection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transection) ProtoMessage() {}

func (x *Transection) ProtoReflect() protoreflect.Message {
	mi := &file_transection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transection.ProtoReflect.Descriptor instead.
func (*Transection) Descriptor() ([]byte, []int) {
	return file_transection_proto_rawDescGZIP(), []int{0}
}

func (x *Transection) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *Transection) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_COMPLETED
}

func (x *Transection) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *Transection) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *Transection) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transection) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *Transection) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreatePaymentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SenderId       string                 `protobuf:"bytes,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ReceiverId     string                 `protobuf:"bytes,2,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	Amount         float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Note           string                 `protobuf:"bytes,4,opt,name=note,proto3" json:"note,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreatePaymentRequest) Reset() {
	*x = CreatePaymentRequest{}
	mi := &file_transection_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRequest) ProtoMessage() {}

func (x *CreatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transection_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_transection_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePaymentRequest) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *CreatePaymentRequest) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *CreatePaymentRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreatePaymentRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *CreatePaymentRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type CreatePaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Status        PaymentStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=pb.PaymentStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentResponse) Reset() {
	*x = CreatePaymentResponse{}
	mi := &file_transection_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentResponse) ProtoMessage() {}

func (x *CreatePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transection_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentResponse.ProtoReflect.Descriptor instead.
func (*CreatePaymentResponse) Descriptor() ([]byte, []int) {
	return file_transection_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePaymentResponse) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *CreatePaymentResponse) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_COMPLETED
}

func (x *CreatePaymentResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetPaymentStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentStatusRequest) Reset() {
	*x = GetPaymentStatusRequest{}
	mi := &file_transection_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentStatusRequest) ProtoMessage() {}

func (x *GetPaymentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transection_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentStatusRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentStatusRequest) Descriptor() ([]byte, []int) {
	return file_transection_proto_rawDescGZIP(), []int{3}
}

func (x *GetPaymentStatusRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

type GetPaymentStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transection   *Transection           `protobuf:"bytes,1,opt,name=transection,proto3" json:"transection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentStatusResponse) Reset() {
	*x = GetPaymentStatusResponse{}
	mi := &file_transection_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentStatusResponse) ProtoMessage() {}

func (x *GetPaymentStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transection_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentStatusResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentStatusResponse) Descriptor() ([]byte, []int) {
	return file_transection_proto_rawDescGZIP(), []int{4}
}

func (x *GetPaymentStatusResponse) GetTransection() *Transection {
	if x != nil {
		return x.Transection
	}
	return nil
}

type GetTransectionHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransectionHistoryRequest) Reset() {
	*x = GetTransectionHistoryRequest{}
	mi := &file_transection_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransectionHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransectionHistoryRequest) ProtoMessage() {}

func (x *GetTransectionHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transection_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransectionHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetTransectionHistoryRequest) Descriptor() ([]byte, []int) {
	return file_transection_proto_rawDescGZIP(), []int{5}
}

func (x *GetTransectionHistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetTransectionHistoryRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetTransectionHistoryRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetTransectionHistoryResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Transection      []*Transection         `protobuf:"bytes,1,rep,name=transection,proto3" json:"transection,omitempty"`
	TotalTransection int64                  `protobuf:"varint,2,opt,name=total_transection,json=totalTransection,proto3" json:"total_transection,omitempty"`
	TotalPage        int64                  `protobuf:"varint,3,opt,name=total_page,json=totalPage,proto3" json:"total_page,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetTransectionHistoryResponse) Reset() {
	*x = GetTransectionHistoryResponse{}
	mi := &file_transection_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransectionHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransectionHistoryResponse) ProtoMessage() {}

func (x *GetTransectionHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transection_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransectionHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetTransectionHistoryResponse) Descriptor() ([]byte, []int) {
	return file_transection_proto_rawDescGZIP(), []int{6}
}

func (x *GetTransectionHistoryResponse) GetTransection() []*Transection {
	if x != nil {
		return x.Transection
	}
	return nil
}

func (x *GetTransectionHistoryResponse) GetTotalTransection() int64 {
	if x != nil {
		return x.TotalTransection
	}
	return 0
}

func (x *GetTransectionHistoryResponse) GetTotalPage() int64 {
	if x != nil {
		return x.TotalPage
	}
	return 0
}

var File_transection_proto protoreflect.FileDescriptor

const file_transection_proto_rawDesc = "" +
	"\n" +
	"\x11transection.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfc\x01\n" +
	"\vTransection\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12)\n" +
	"\x06status\x18\x02 \x01(\x0e2\x11.pb.PaymentStatusR\x06status\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\tR\bsenderId\x12\x1f\n" +
	"\vreceiver_id\x18\x04 \x01(\tR\n" +
	"receiverId\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x01R\x06amount\x12\x12\n" +
	"\x04note\x18\x06 \x01(\tR\x04note\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xa9\x01\n" +
	"\x14CreatePaymentRequest\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\tR\bsenderId\x12\x1f\n" +
	"\vreceiver_id\x18\x02 \x01(\tR\n" +
	"receiverId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x12\n" +
	"\x04note\x18\x04 \x01(\tR\x04note\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\"\x9c\x01\n" +
	"\x15CreatePaymentResponse\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12)\n" +
	"\x06status\x18\x02 \x01(\x0e2\x11.pb.PaymentStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"8\n" +
	"\x17GetPaymentStatusRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\"M\n" +
	"\x18GetPaymentStatusResponse\x121\n" +
	"\vtransection\x18\x01 \x01(\v2\x0f.pb.TransectionR\vtransection\"e\n" +
	"\x1cGetTransectionHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\"\x9e\x01\n" +
	"\x1dGetTransectionHistoryResponse\x121\n" +
	"\vtransection\x18\x01 \x03(\v2\x0f.pb.TransectionR\vtransection\x12+\n" +
	"\x11total_transection\x18\x02 \x01(\x03R\x10totalTransection\x12\x1d\n" +
	"\n" +
	"total_page\x18\x03 \x01(\x03R\ttotalPage*\x80\x01\n" +
	"\rPaymentStatus\x12\x1c\n" +
	"\x18PAYMENT_STATUS_COMPLETED\x10\x00\x12\x18\n" +
	"\x14PAYMENT_STATUS_ERROR\x10\x01\x12\x1a\n" +
	"\x16PAYMENT_STATUS_PENDING\x10\x02\x12\x1b\n" +
	"\x17PAYMENT_STATUS_REVERSED\x10\x032\x82\x02\n" +
	"\rWalletService\x12D\n" +
	"\rCreatePayment\x12\x18.pb.CreatePaymentRequest\x1a\x19.pb.CreatePaymentResponse\x12M\n" +
	"\x10GetPaymentStatus\x12\x1b.pb.GetPaymentStatusRequest\x1a\x1c.pb.GetPaymentStatusResponse\x12\\\n" +
	"\x15GetTransectionHistory\x12 .pb.GetTransectionHistoryRequest\x1a!.pb.GetTransectionHistoryResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_transection_proto_rawDescOnce sync.Once
	file_transection_proto_rawDescData []byte
)

func file_transection_proto_rawDescGZIP() []byte {
	file_transection_proto_rawDescOnce.Do(func() {
		file_transection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transection_proto_rawDesc), len(file_transection_proto_rawDesc)))
	})
	return file_transection_proto_rawDescData
}

var file_transection_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_transection_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_transection_proto_goTypes = []any{
	(PaymentStatus)(0),                    // 0: pb.PaymentStatus
	(*Transection)(nil),                   // 1: pb.Transection
	(*CreatePaymentRequest)(nil),          // 2: pb.CreatePaymentRequest
	(*CreatePaymentResponse)(nil),         // 3: pb.CreatePaymentResponse
	(*GetPaymentStatusRequest)(nil),       // 4: pb.GetPaymentStatusRequest
	(*GetPaymentStatusResponse)(nil),      // 5: pb.GetPaymentStatusResponse
	(*GetTransectionHistoryRequest)(nil),  // 6: pb.GetTransectionHistoryRequest
	(*GetTransectionHistoryResponse)(nil), // 7: pb.GetTransectionHistoryResponse
	(*timestamppb.Timestamp)(nil),         // 8: google.protobuf.Timestamp
}
var file_transection_proto_depIdxs = []int32{
	0, // 0: pb.Transection.status:type_name -> pb.PaymentStatus
	8, // 1: pb.Transection.created_at:type_name -> google.protobuf.Timestamp
	0, // 2: pb.CreatePaymentResponse.status:type_name -> pb.PaymentStatus
	8, // 3: pb.CreatePaymentResponse.created_at:type_name -> google.protobuf.Timestamp
	1, // 4: pb.GetPaymentStatusResponse.transection:type_name -> pb.Transection
	1, // 5: pb.GetTransectionHistoryResponse.transection:type_name -> pb.Transection
	2, // 6: pb.WalletService.CreatePayment:input_type -> pb.CreatePaymentRequest
	4, // 7: pb.WalletService.GetPaymentStatus:input_type -> pb.GetPaymentStatusRequest
	6, // 8: pb.WalletService.GetTransectionHistory:input_type -> pb.GetTransectionHistoryRequest
	3, // 9: pb.WalletService.CreatePayment:output_type -> pb.CreatePaymentResponse
	5, // 10: pb.WalletService.GetPaymentStatus:output_type -> pb.GetPaymentStatusResponse
	7, // 11: pb.WalletService.GetTransectionHistory:output_type -> pb.GetTransectionHistoryResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_transection_proto_init() }
func file_transection_proto_init() {
	if File_transection_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transection_proto_rawDesc), len(file_transection_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transection_proto_goTypes,
		DependencyIndexes: file_transection_proto_depIdxs,
		EnumInfos:         file_transection_proto_enumTypes,
		MessageInfos:      file_transection_proto_msgTypes,
	}.Build()
	File_transection_proto = out.File
	file_transection_proto_goTypes = nil
	file_transection_proto_depIdxs = nil
}
